XPos294/WebApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using ViewModel;
using WebApp.Services;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Administrator, Category")]
    public class CategoryController : Controller
    {

        private readonly ILogger<CategoryController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string WebApiBaseUrl;

        private readonly CategoryService catServ;

        public CategoryController(ILogger<CategoryController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            WebApiBaseUrl = _configuration.GetValue<string>("WebApiBaseUrl");
            catServ = new CategoryService(configuration);
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List()
        {
            List<CategoryViewModel> list = await catServ.GetAll();
            return PartialView("_List", list);
        }

        public IActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await catServ.Create(model);
                if (result.Success)
                {
                    ViewBag.title = "Create";
                    ViewBag.subtitle = "Created";
                    return PartialView("_Success", model);
                }
                else
                {
                    ViewBag.ErrorMessage = result.Message;
                }

            }
            return PartialView("_Create", model);
        }

        public async Task<IActionResult> Edit(int id)
        {

            CategoryViewModel result = await catServ.GetById(id);
            if (result != null)
            {
                return PartialView("_Edit", result);
            }
            return PartialView("_Edit", result);

        }


        [HttpPost]
        public async Task<IActionResult> Edit(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await catServ.Update(model);

                if (result.Success)
                {
                    ViewBag.title = "Edit";
                    ViewBag.subtitle = "Edited";
                    return PartialView("_Success", model);
                }
                else
                {
                    ViewBag.ErrorMessage = result.Message;
                }


            }
            return PartialView("_Edit", model);
        }


        public async Task<IActionResult> Details(int id)
        {

            CategoryViewModel result = await catServ.GetById(id);
          
                    if (result != null)
                    {
                        return PartialView("_Details", result);
                    }
            return PartialView("_Details", result);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            CategoryViewModel result = await catServ.GetById(id);
                    if (result != null)
                    {
                        return PartialView("_Delete", result);
                    }
            return PartialView("_Delete", result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await catServ.Delete(model);
                if (result.Success)
                {
                    ViewBag.title = "Delete";
                    ViewBag.subtitle = "Deleted";
                    return PartialView("_Success", model);
                }
                else
                {
                    ViewBag.ErrorMessage = result.Message;
                }

            }
            return PartialView("_Delete", model);
        }
    }
}

XPos294/WebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using ViewModel;
using WebApp.Services;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Administrator,Product")]
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;

        private readonly VariantService varServ;
        private readonly ProductService proServ;

        public ProductController(ILogger<ProductController> logger, IConfiguration configuration)
        {
            _logger = logger;
            varServ = new VariantService(configuration);
            proServ = new ProductService(configuration);
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List()
        {
            List<ProductViewModel> list = await proServ.GetAll();
            return PartialView("_List", list);
        }

        public async Task<IActionResult> Create()
        {
            List<VariantViewModel> variantList = await varServ.GetAll();
            ViewBag.VariantList = new SelectList(variantList, "Id", "Name");
            return PartialView("_Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await proServ.Create(model);
                if (result.Success)
                {
                    ViewBag.Title = "Create";
                    ViewBag.Body = "Created!";
                    return PartialView("_Success", model);
                }
                else
                    ViewBag.ErrorMessage = result.Message;
            }
            List<VariantViewModel> variantList = await varServ.GetAll();
            ViewBag.VariantList = new SelectList(variantList, "Id", "Name");
            return PartialView("_Create", model);
        }

        public async Task<IActionResult> Edit(long id)
        {
            List<VariantViewModel> variantList = await varServ.GetAll();
            ViewBag.VariantList = new SelectList(variantList, "Id", "Name");
            ProductViewModel result = await proServ.GetById(id);
            return PartialView("_Edit", result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await proServ.Update(model);
                if (result.Success)
                {
                    ViewBag.Title = "Edit";
                    ViewBag.Body = "Changed!";
                    return PartialView("_Success", model);
                }
                else
                    ViewBag.ErrorMessage = result.Message;
            }
            List<VariantViewModel> variantList = await varServ.GetAll();
            ViewBag.VariantList = new SelectList(variantList, "Id", "Name");
            return PartialView("_Edit", model);
        }

        public async Task<IActionResult> Details(int id)
        {
            ProductViewModel result = await proServ.GetById(id);
            return PartialView("_Details", result);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(long id)
        {
            ProductViewModel result = await proServ.GetById(id);
            return PartialView("_Delete", result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await proServ.Delete(model);
                if (result.Success)
                {
                    ViewBag.Title = "Delete";
                    ViewBag.Body = "Deleted";
                    return PartialView("_Success", model);
                }
                else
                    ViewBag.ErrorMessage = result.Message;
            }
            return PartialView("_Delete", model);
        }
    }
}

XPos294/WebApp/Controllers/VariantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using ViewModel;
using WebApp.Services;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Administrator, Variant")]
    public class VariantController : Controller
    {

        private readonly ILogger<VariantController> _logger;
        private readonly IConfiguration _configuration;
        private readonly string WebApiBaseUrl;

        private readonly CategoryService catServ;
        private readonly VariantService varServ;

        public VariantController(ILogger<VariantController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            WebApiBaseUrl = _configuration.GetValue<string>("WebApiBaseUrl");
            catServ = new CategoryService(configuration);
            varServ = new VariantService(configuration);

        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List()
        {
            List<VariantViewModel> list = await varServ.GetAll();
            return PartialView("_List", list);
        }

        public async Task<IActionResult> Create()
        {
            List<CategoryViewModel> categorylist = await catServ.GetAll();
            ViewBag.CategoryList = new SelectList(categorylist, "Id", "Name");
            return PartialView("_Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(VariantViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await varServ.Create(model);

                        if (result.Success)
                        {
                            ViewBag.title = "Create";
                            ViewBag.subtitle = "Created";
                            return PartialView("_Success", model);
                        }
                        else
                        {
                            ViewBag.ErrorMessage = result.Message;
                        }
            }
            List<CategoryViewModel> categorylist = await catServ.GetAll();
            ViewBag.CategoryList = new SelectList(categorylist, "Id", "Name");
            return PartialView("_Create", model);
        }

        public async Task<IActionResult> Edit(long id)
        {
            List<CategoryViewModel> categorylist = await catServ.GetAll();
            ViewBag.CategoryList = new SelectList(categorylist, "Id", "Name");
            VariantViewModel result = await varServ.GetById(id);
            return PartialView("_Edit", result);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(VariantViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await varServ.Update(model);
                        if (result.Success)
                        {
                            ViewBag.title = "Edit";
                            ViewBag.subtitle = "Edited";
                            return PartialView("_Success", model);
                        }
                        else
                        {
                            ViewBag.ErrorMessage = result.Message;
                        }
            }
            List<CategoryViewModel> categorylist = await catServ.GetAll();
            ViewBag.CategoryList = new SelectList(categorylist, "Id", "Name");
            return PartialView("_Edit", model);
        }


        public async Task<IActionResult> Details(int id)
        {

            VariantViewModel result = await varServ.GetById(id);
            return PartialView("_Details", result);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            VariantViewModel result = await varServ.GetById(id);
            return PartialView("_Delete", result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(VariantViewModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseResult result = await varServ.Delete(model);
                        if (result.Success)
                        {
                            ViewBag.title = "Delete";
                            ViewBag.subtitle = "Deleted";
                            return PartialView("_Success", model);
                        }
                        else
                        {
                            ViewBag.ErrorMessage = result.Message;
                        }
            }
            return PartialView("_Delete", model);
        }
    }
}

XPos294/WebApp/Views/Shared/_Layout - Copy.cshtml
@using WebApp.Security
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebKu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/~/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" >
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebKu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ContextAccessor.GetMenuRoles() [0] == "Administrator")
                        {    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Variant" asp-action="Index">Variant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Perpustakaan" asp-action="Index">Perpustakaan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                         </li>
                        }
                        else
                        {
                            foreach (var item in ContextAccessor.GetMenuRoles())
                            {
                                 <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="@item" asp-action="Index">@item</a>
                                 </li>
                            }
                        }
                    </ul>
                </div>
                <div class="row">
                    <div class="col-auto">
                        @if (ContextAccessor.IsAuthenticated())
                        {   
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark">Log in as @ContextAccessor.GetFullName()</a>
                            </li>
                             <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
                            </li>
                        </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
                                 </li>
                            </ul>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebCool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/~/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

XPos294/WebApp/Views/Shared/_SideBarMenu.cshtml
@using WebApp.Security
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    List<string> defaultMenu = new List<string>() { "Category", "Variant", "Product", "Order" };
    List<string> userMenu = ContextAccessor.GetMenuRoles();
}
<!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-header">MENU</li>
        @if (userMenu.Count > 0)
        {
            @if (ContextAccessor.GetMenuRoles()[0] == "Administrator")
            {
                foreach (var item in defaultMenu)
                {

                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="@item" asp-action="Index">
                            <i class="nav-icon far fa-image"></i>
                            <p>
                                @item
                            </p>
                        </a>
                    </li>
                }
            }
            else
            {
                foreach (var item in ContextAccessor.GetMenuRoles())
                {
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="@item" asp-action="Index">
                            <i class="nav-icon far fa-image"></i>
                            <p>
                                @item
                            </p>
                        </a>
                    </li>
                }
            }
            
        }
        @if (ContextAccessor.IsAuthenticated())
            {
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">
                       <i class="fa fa-sign-out" aria-hidden="true"></i>
                        <p>
                            Logout
                        </p>
                    </a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Index">
                        <i class="fa fa-sign-in" aria-hidden="true"></i>
                        <p>
                            Login
                        </p>
                    </a>
                </li>
            }
    </ul>
</nav>
<!-- /.sidebar-menu -->

XPos294/WebApp/Views/Shared/_UserProfile.cshtml
@using WebApp.Security
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
   <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="~/dist/img/aah.png" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">@ContextAccessor.GetFullName()</a>
        </div>
      </div>